# swagger-cli bundle api/openapi/index.yaml -o api/openapi/summary.yaml --type yaml
# oapi-codegen -generate types -o ./internal/infrastructure/http/api_dto/api_dto.go -package api_dto ./api/openapi/summary.yaml

openapi: 3.0.3
info:
  title: Api
  version: 1.0.0

paths:
  $ref: './user.yaml#/paths'